Documentación Técnica: EnemyHealthSystem Class Reference
EnemyHealthSystem Class Reference
Public Member Functions
void TakeDamage (int damage, Vector2 attackerPosition)
Punto de entrada de daño para el enemigo. Reduce la vida, aplica knockback y verifica si el enemigo debe morir.
Public Attributes
int maxHealth = 50
Vida máxima del enemigo. Define cuántos puntos de daño puede absorber antes de morir. Configurable por tipo de enemigo desde el Inspector.
int currentHealth
Vida actual del enemigo en tiempo real. Se inicializa igual a maxHealth en Start(). Visible en el Inspector para debug durante la partida.
float knockbackForce = 5f
Fuerza del empuje físico (knockback) que recibe el enemigo al ser golpeado. Configurable desde el Inspector. Valor más alto = mayor desplazamiento.
float knockbackDuration = 0.3f
Duración en segundos del hit-stun: tiempo mínimo que debe pasar antes de que el enemigo pueda recibir otro knockback. Evita que golpes rápidos apilen fuerzas y lo lancen fuera de la pantalla.
Private Member Functions
void Start ()
Start() — Se ejecuta una vez al activarse el enemigo en escena. Inicializa la vida al máximo y obtiene el Rigidbody2D.
void ApplyHit (Vector2 attackerPosition)
Aplica el knockback físico al enemigo cuando recibe un golpe. Controla el hit-stun para evitar que fuerzas se acumulen.
void EndHit ()
Finaliza el hit-stun y permite que el enemigo reciba knockback nuevamente. Se llama automáticamente mediante Invoke() al vencer knockbackDuration.
void Die ()
Destruye el enemigo al quedarse sin vida. Usa un delay de 0.5 segundos para permitir efectos visuales de muerte (animaciones, partículas, sonidos) antes de eliminar el objeto.
Private Attributes
Rigidbody2D rb
Referencia al Rigidbody2D del enemigo. Se obtiene automáticamente en Start(). Necesario para aplicar knockback.
bool isHit = false
Flag de hit-stun activo. true = el enemigo está en hit-stun y no puede recibir otro knockback. false = el enemigo puede recibir daño con efecto físico completo. Previene el "stacking" de fuerzas por golpes consecutivos rápidos.
Detailed Description
Definition at line 26 of file EnemyHealthSystem.cs.
Member Function Documentation
ApplyHit()
void EnemyHealthSystem.ApplyHit (Vector2 attackerPosition) inline private
Aplica el knockback físico al enemigo cuando recibe un golpe. Controla el hit-stun para evitar que fuerzas se acumulen.
CUÁNDO SE EJECUTA: Llamado internamente desde TakeDamage(). QUÉ AFECTA: Rigidbody2D (velocidad y fuerza), flag isHit.
NOTA: Si isHit ya está activo, el método retorna sin hacer nada. Esto es intencional para evitar stacking de knockback.
Parameters
attackerPosition Posición desde donde vino el ataque.
Definition at line 135 of file EnemyHealthSystem.cs.
Referenced by TakeDamage().
Die()
void EnemyHealthSystem.Die () inline private
Destruye el enemigo al quedarse sin vida. Usa un delay de 0.5 segundos para permitir efectos visuales de muerte (animaciones, partículas, sonidos) antes de eliminar el objeto.
CUÁNDO SE EJECUTA: Llamado desde TakeDamage() cuando currentHealth llega a 0.
Definition at line 172 of file EnemyHealthSystem.cs.
Referenced by TakeDamage().
EndHit()
void EnemyHealthSystem.EndHit () inline private
Finaliza el hit-stun y permite que el enemigo reciba knockback nuevamente. Se llama automáticamente mediante Invoke() al vencer knockbackDuration.
Definition at line 160 of file EnemyHealthSystem.cs.
Referenced by ApplyHit().
Start()
void EnemyHealthSystem.Start () inline private
Start() — Se ejecuta una vez al activarse el enemigo en escena. Inicializa la vida al máximo y obtiene el Rigidbody2D.
Definition at line 84 of file EnemyHealthSystem.cs.
TakeDamage()
void EnemyHealthSystem.TakeDamage (int damage, Vector2 attackerPosition) inline
Punto de entrada de daño para el enemigo. Reduce la vida, aplica knockback y verifica si el enemigo debe morir.
CUÁNDO SE LLAMA: Desde Hitbox.cs o ExtendedHitbox.cs cuando un golpe conecta. QUÉ AFECTA: currentHealth, física del Rigidbody2D, y destrucción del objeto.
Parameters
damage Cantidad de puntos de vida a restar.
attackerPosition Posición del atacante para calcular dirección del knockback.
Definition at line 103 of file EnemyHealthSystem.cs.
Referenced by ExtendedHitbox.OnTriggerEnter2D(), EnemyHealthSystemTests.TakeDamage_EnemyDiesWhenHealthReachesZero(), EnemyHealthSystemTests.TakeDamage_HealthDoesNotGoBelowZero(), EnemyHealthSystemTests.TakeDamage_KnockbackPushesAwayFromAttacker(), EnemyHealthSystemTests.TakeDamage_ReducesHealthByDamageAmount(), and EnemyHealthSystemTests.TakeDamage_SecondHitDuringHitStun_DoesNotApplyKnockbackAgain().
Member Data Documentation
currentHealth
int EnemyHealthSystem.currentHealth
Vida actual del enemigo en tiempo real. Se inicializa igual a maxHealth en Start(). Visible en el Inspector para debug durante la partida.
Definition at line 43 of file EnemyHealthSystem.cs.
Referenced by ExtendedHitboxTests.ExtendedHitbox_OnlyDamagesWhenAttackIsActive(), Start(), TakeDamage(), EnemyHealthSystemTests.TakeDamage_EnemyDiesWhenHealthReachesZero(), EnemyHealthSystemTests.TakeDamage_HealthDoesNotGoBelowZero(), and EnemyHealthSystemTests.TakeDamage_ReducesHealthByDamageAmount().
isHit
bool EnemyHealthSystem.isHit = false private
Flag de hit-stun activo. true = el enemigo está en hit-stun y no puede recibir otro knockback. false = el enemigo puede recibir daño con efecto físico completo. Previene el "stacking" de fuerzas por golpes consecutivos rápidos.
Definition at line 74 of file EnemyHealthSystem.cs.
Referenced by ApplyHit(), and EndHit().
knockbackDuration
float EnemyHealthSystem.knockbackDuration = 0.3f
Duración en segundos del hit-stun: tiempo mínimo que debe pasar antes de que el enemigo pueda recibir otro knockback. Evita que golpes rápidos apilen fuerzas y lo lancen fuera de la pantalla.
Definition at line 56 of file EnemyHealthSystem.cs.
Referenced by ApplyHit().
knockbackForce
float EnemyHealthSystem.knockbackForce = 5f
Fuerza del empuje físico (knockback) que recibe el enemigo al ser golpeado. Configurable desde el Inspector. Valor más alto = mayor desplazamiento.
Definition at line 49 of file EnemyHealthSystem.cs.
Referenced by ApplyHit().
maxHealth
int EnemyHealthSystem.maxHealth = 50
Vida máxima del enemigo. Define cuántos puntos de daño puede absorber antes de morir. Configurable por tipo de enemigo desde el Inspector.
Definition at line 36 of file EnemyHealthSystem.cs.
Referenced by Start(), EnemyHealthSystemTests.TakeDamage_EnemyDiesWhenHealthReachesZero(), and EnemyHealthSystemTests.TakeDamage_HealthDoesNotGoBelowZero().
rb
Rigidbody2D EnemyHealthSystem.rb private
Referencia al Rigidbody2D del enemigo. Se obtiene automáticamente en Start(). Necesario para aplicar knockback.
Definition at line 66 of file EnemyHealthSystem.cs.
Referenced by ApplyHit(), and Start().
The documentation for this class was generated from the following file:
spritesheets/Scripts/EnemyHealthSystem.cs