Documentación Técnica: EnemyHealthSystemTests Class Reference
EnemyHealthSystemTests Class Reference
TEST SUITE: EnemyHealthSystem.
Public Member Functions
void TearDown ()
Se ejecuta después de cada test. Elimina el enemigo creado para evitar contaminación entre pruebas.
IEnumerator TakeDamage_ReducesHealthByDamageAmount ()
Verifica que el enemigo pierde vida correctamente cuando recibe daño.
IEnumerator TakeDamage_HealthDoesNotGoBelowZero ()
Verifica que la vida nunca baja de 0, incluso si el daño es mayor que la vida actual.
IEnumerator TakeDamage_KnockbackPushesAwayFromAttacker ()
Verifica que el enemigo es empujado en dirección opuesta al atacante cuando recibe daño.
IEnumerator TakeDamage_SecondHitDuringHitStun_DoesNotApplyKnockbackAgain ()
Verifica que durante el hit-stun el enemigo no recibe un segundo knockback inmediatamente.
IEnumerator TakeDamage_EnemyDiesWhenHealthReachesZero ()
Verifica que el enemigo se destruye cuando su vida llega a 0.
Private Member Functions
EnemyHealthSystem CreateEnemy (Vector3 position=default)
Crea un enemigo simulado con:
Private Attributes
GameObject _enemyGO
Detailed Description
TEST SUITE: EnemyHealthSystem.
PROPÓSITO: Validar el sistema de vida de los enemigos, incluyendo:
Aplicación de daño
Límites de vida (no menor a 0)
Knockback al recibir daño
Hit-stun (inmunidad temporal)
Muerte del enemigo cuando la vida llega a 0
USO: Estas pruebas simulan enemigos en runtime y verifican su comportamiento sin necesidad de escena Unity.
DEPENDENCIAS:
Rigidbody2D (para knockback físico)
Unity Physics2D (FixedUpdate)
Destrucción de GameObjects (Destroy)
Definition at line 26 of file EnemyHealthSystemTests.cs.
Member Function Documentation
CreateEnemy()
EnemyHealthSystem EnemyHealthSystemTests.CreateEnemy (Vector3 position = default) inline private
Crea un enemigo simulado con:
Rigidbody2D sin gravedad (controlado)
EnemyHealthSystem con knockback configurado
USO: Permite generar enemigos consistentes para todas las pruebas.
Definition at line 44 of file EnemyHealthSystemTests.cs.
Referenced by TakeDamage_EnemyDiesWhenHealthReachesZero(), TakeDamage_HealthDoesNotGoBelowZero(), TakeDamage_KnockbackPushesAwayFromAttacker(), TakeDamage_ReducesHealthByDamageAmount(), and TakeDamage_SecondHitDuringHitStun_DoesNotApplyKnockbackAgain().
TakeDamage_EnemyDiesWhenHealthReachesZero()
IEnumerator EnemyHealthSystemTests.TakeDamage_EnemyDiesWhenHealthReachesZero () inline
Verifica que el enemigo se destruye cuando su vida llega a 0.
Definition at line 181 of file EnemyHealthSystemTests.cs.
TakeDamage_HealthDoesNotGoBelowZero()
IEnumerator EnemyHealthSystemTests.TakeDamage_HealthDoesNotGoBelowZero () inline
Verifica que la vida nunca baja de 0, incluso si el daño es mayor que la vida actual.
Definition at line 107 of file EnemyHealthSystemTests.cs.
TakeDamage_KnockbackPushesAwayFromAttacker()
IEnumerator EnemyHealthSystemTests.TakeDamage_KnockbackPushesAwayFromAttacker () inline
Verifica que el enemigo es empujado en dirección opuesta al atacante cuando recibe daño.
Definition at line 130 of file EnemyHealthSystemTests.cs.
TakeDamage_ReducesHealthByDamageAmount()
IEnumerator EnemyHealthSystemTests.TakeDamage_ReducesHealthByDamageAmount () inline
Verifica que el enemigo pierde vida correctamente cuando recibe daño.
Definition at line 80 of file EnemyHealthSystemTests.cs.
TakeDamage_SecondHitDuringHitStun_DoesNotApplyKnockbackAgain()
IEnumerator EnemyHealthSystemTests.TakeDamage_SecondHitDuringHitStun_DoesNotApplyKnockbackAgain () inline
Verifica que durante el hit-stun el enemigo no recibe un segundo knockback inmediatamente.
Definition at line 154 of file EnemyHealthSystemTests.cs.
TearDown()
void EnemyHealthSystemTests.TearDown () inline
Se ejecuta después de cada test. Elimina el enemigo creado para evitar contaminación entre pruebas.
Definition at line 66 of file EnemyHealthSystemTests.cs.
Member Data Documentation
_enemyGO
GameObject EnemyHealthSystemTests._enemyGO private
Definition at line 31 of file EnemyHealthSystemTests.cs.
Referenced by CreateEnemy(), TakeDamage_EnemyDiesWhenHealthReachesZero(), TakeDamage_HealthDoesNotGoBelowZero(), TakeDamage_KnockbackPushesAwayFromAttacker(), TakeDamage_ReducesHealthByDamageAmount(), TakeDamage_SecondHitDuringHitStun_DoesNotApplyKnockbackAgain(), and TearDown().
The documentation for this class was generated from the following file:
Tests/PlayMode/EnemyHealthSystemTests.cs