Documentación Técnica: HealthSystemTests Class Reference
HealthSystemTests Class Reference
TESTS: HealthSystem.
Public Member Functions
void TearDown ()
Limpieza después de cada test para evitar interferencia entre pruebas.
IEnumerator TakeDamage_ReducesHealthByDamageAmount ()
CASO 1: El daño recibido debe reducir la vida correctamente.
IEnumerator TakeDamage_HealthDoesNotGoBelowZero ()
CASO 2: La vida nunca debe ser menor a 0 incluso con daño excesivo.
IEnumerator TakeDamage_KnockbackPushesAwayFromAttacker ()
CASO 3: El knockback debe empujar al jugador en dirección opuesta al atacante.
IEnumerator TakeDamage_PlayerMovementDisabledDuringHitStun ()
CASO 4: Durante el hitstun, el movimiento del jugador debe quedar deshabilitado.
IEnumerator AfterKnockbackDuration_PlayerMovementIsReenabled ()
CASO 5: Después del knockback, el control del jugador debe restaurarse automáticamente.
Private Member Functions
HealthSystem CreatePlayer (Vector3 position=default)
Crea un jugador completo con:
Private Attributes
GameObject _playerGO
Detailed Description
TESTS: HealthSystem.
PROPÓSITO: Validar el sistema de vida del jugador:
Reducción de vida
Límite mínimo (0)
Knockback físico
Estado de hitstun
Restauración del control del jugador
USO: Ejecutar en Unity Test Runner (PlayMode). Cada test crea su propio jugador aislado.
Definition at line 21 of file HealthSystemTests.cs.
Member Function Documentation
AfterKnockbackDuration_PlayerMovementIsReenabled()
IEnumerator HealthSystemTests.AfterKnockbackDuration_PlayerMovementIsReenabled () inline
CASO 5: Después del knockback, el control del jugador debe restaurarse automáticamente.
Definition at line 171 of file HealthSystemTests.cs.
CreatePlayer()
HealthSystem HealthSystemTests.CreatePlayer (Vector3 position = default) inline private
Crea un jugador completo con:
Rigidbody2D sin gravedad (determinista)
Collider base
PlayerMovement (dependencia del sistema de daño)
HealthSystem (sistema bajo prueba)
Definition at line 33 of file HealthSystemTests.cs.
Referenced by AfterKnockbackDuration_PlayerMovementIsReenabled(), TakeDamage_HealthDoesNotGoBelowZero(), TakeDamage_KnockbackPushesAwayFromAttacker(), TakeDamage_PlayerMovementDisabledDuringHitStun(), and TakeDamage_ReducesHealthByDamageAmount().
TakeDamage_HealthDoesNotGoBelowZero()
IEnumerator HealthSystemTests.TakeDamage_HealthDoesNotGoBelowZero () inline
CASO 2: La vida nunca debe ser menor a 0 incluso con daño excesivo.
Definition at line 94 of file HealthSystemTests.cs.
TakeDamage_KnockbackPushesAwayFromAttacker()
IEnumerator HealthSystemTests.TakeDamage_KnockbackPushesAwayFromAttacker () inline
CASO 3: El knockback debe empujar al jugador en dirección opuesta al atacante.
Definition at line 118 of file HealthSystemTests.cs.
TakeDamage_PlayerMovementDisabledDuringHitStun()
IEnumerator HealthSystemTests.TakeDamage_PlayerMovementDisabledDuringHitStun () inline
CASO 4: Durante el hitstun, el movimiento del jugador debe quedar deshabilitado.
Definition at line 145 of file HealthSystemTests.cs.
TakeDamage_ReducesHealthByDamageAmount()
IEnumerator HealthSystemTests.TakeDamage_ReducesHealthByDamageAmount () inline
CASO 1: El daño recibido debe reducir la vida correctamente.
Definition at line 67 of file HealthSystemTests.cs.
TearDown()
void HealthSystemTests.TearDown () inline
Limpieza después de cada test para evitar interferencia entre pruebas.
Definition at line 56 of file HealthSystemTests.cs.
Member Data Documentation
_playerGO
GameObject HealthSystemTests._playerGO private
Definition at line 24 of file HealthSystemTests.cs.
Referenced by AfterKnockbackDuration_PlayerMovementIsReenabled(), CreatePlayer(), TakeDamage_HealthDoesNotGoBelowZero(), TakeDamage_KnockbackPushesAwayFromAttacker(), TakeDamage_PlayerMovementDisabledDuringHitStun(), TakeDamage_ReducesHealthByDamageAmount(), and TearDown().
The documentation for this class was generated from the following file:
Tests/PlayMode/HealthSystemTests.cs