var searchData=
[
  ['para_20acceder_20a_20estados_20privados_0',['- Se usa Reflection para acceder a estados privados.',['../class_player_movement_tests.html#autotoc_md6',1,'']]],
  ['para_20simular_20el_20ciclo_20real_1',['- Update() se invoca manualmente para simular el ciclo real.',['../class_player_defense_tests.html#autotoc_md3',1,'']]],
  ['player_20attack_2',['PRUEBAS DE PLAYER ATTACK',['../class_player_attack_tests.html#autotoc_md0',1,'']]],
  ['player_20defense_20tests_3',['SISTEMA: PLAYER DEFENSE TESTS',['../class_player_defense_tests.html#autotoc_md2',1,'']]],
  ['player_20movement_20tests_4',['SISTEMA: PLAYER MOVEMENT TESTS',['../class_player_movement_tests.html#autotoc_md5',1,'']]],
  ['playerattack_5',['PlayerAttack',['../class_player_attack.html',1,'']]],
  ['playerattack_6',['playerAttack',['../class_extended_hitbox.html#a467ce86a30d8722edb4070529be12b68',1,'ExtendedHitbox']]],
  ['playerattack_2ecs_7',['PlayerAttack.cs',['../_player_attack_8cs.html',1,'']]],
  ['playerattacktests_8',['PlayerAttackTests',['../class_player_attack_tests.html',1,'']]],
  ['playerattacktests_2ecs_9',['PlayerAttackTests.cs',['../_player_attack_tests_8cs.html',1,'']]],
  ['playerdefense_10',['PlayerDefense',['../class_player_defense.html',1,'']]],
  ['playerdefense_2ecs_11',['PlayerDefense.cs',['../_player_defense_8cs.html',1,'']]],
  ['playerdefensetests_12',['PlayerDefenseTests',['../class_player_defense_tests.html',1,'']]],
  ['playerdefensetests_2ecs_13',['PlayerDefenseTests.cs',['../_player_defense_tests_8cs.html',1,'']]],
  ['playermovement_14',['PlayerMovement',['../class_player_movement.html',1,'']]],
  ['playermovement_15',['playerMovement',['../class_player_attack.html#aff13fa0f28b4d333cd7e3d3ad6214f88',1,'PlayerAttack']]],
  ['playermovement_2ecs_16',['PlayerMovement.cs',['../_player_movement_8cs.html',1,'']]],
  ['playermovementtests_17',['PlayerMovementTests',['../class_player_movement_tests.html',1,'']]],
  ['playermovementtests_2ecs_18',['PlayerMovementTests.cs',['../_player_movement_tests_8cs.html',1,'']]],
  ['principales_19',['Clases Principales',['../index.html#autotoc_md11',1,'']]],
  ['privados_20',['- Se usa Reflection para acceder a estados privados.',['../class_player_movement_tests.html#autotoc_md6',1,'']]],
  ['proyecto_21',['Estructura del Proyecto',['../index.html#autotoc_md9',1,'']]],
  ['prueba_22',['Prueba',['../class_prueba.html',1,'']]],
  ['prueba_2ecs_23',['Prueba.cs',['../_prueba_8cs.html',1,'']]],
  ['pruebas_20de_20player_20attack_24',['PRUEBAS DE PLAYER ATTACK',['../class_player_attack_tests.html#autotoc_md0',1,'']]],
  ['punchcooldown_25',['punchCooldown',['../class_player_attack.html#af5b081ae192a762efa4ff18a52702486',1,'PlayerAttack']]],
  ['punchcooldown_5fpunchreadyrestoresaftercooldown_26',['PunchCooldown_PunchReadyRestoresAfterCooldown',['../class_player_attack_tests.html#a2e83e24b4869e75cd02d4f991960f8f2',1,'PlayerAttackTests']]],
  ['punchhitbox_27',['punchHitbox',['../class_player_attack.html#af460ec9e43a1027044ac9a9b4e706933',1,'PlayerAttack']]],
  ['punchhitbox_5fdeactivatesafterattackduration_28',['PunchHitbox_DeactivatesAfterAttackDuration',['../class_player_attack_tests.html#ad05b0e5c7a7698acaadd2c660ad45d08',1,'PlayerAttackTests']]],
  ['punchkey_29',['punchKey',['../class_player_attack.html#aa4f16c2b62e0804898250fa244fdda4f',1,'PlayerAttack']]],
  ['punchready_30',['punchReady',['../class_player_attack.html#ad1649114de2177e3c3ed68b45fc1f1f9',1,'PlayerAttack']]]
];
