var annotated_dup =
[
    [ "TMPro", "namespace_t_m_pro.html", [
      [ "Examples", "namespace_t_m_pro_1_1_examples.html", [
        [ "Benchmark01", "class_t_m_pro_1_1_examples_1_1_benchmark01.html", null ],
        [ "Benchmark01_UGUI", "class_t_m_pro_1_1_examples_1_1_benchmark01___u_g_u_i.html", null ],
        [ "Benchmark02", "class_t_m_pro_1_1_examples_1_1_benchmark02.html", null ],
        [ "Benchmark03", "class_t_m_pro_1_1_examples_1_1_benchmark03.html", null ],
        [ "Benchmark04", "class_t_m_pro_1_1_examples_1_1_benchmark04.html", null ],
        [ "CameraController", "class_t_m_pro_1_1_examples_1_1_camera_controller.html", null ],
        [ "ObjectSpin", "class_t_m_pro_1_1_examples_1_1_object_spin.html", null ],
        [ "ShaderPropAnimator", "class_t_m_pro_1_1_examples_1_1_shader_prop_animator.html", null ],
        [ "SimpleScript", "class_t_m_pro_1_1_examples_1_1_simple_script.html", null ],
        [ "SkewTextExample", "class_t_m_pro_1_1_examples_1_1_skew_text_example.html", null ],
        [ "TeleType", "class_t_m_pro_1_1_examples_1_1_tele_type.html", null ],
        [ "TextConsoleSimulator", "class_t_m_pro_1_1_examples_1_1_text_console_simulator.html", null ],
        [ "TextMeshProFloatingText", "class_t_m_pro_1_1_examples_1_1_text_mesh_pro_floating_text.html", null ],
        [ "TextMeshSpawner", "class_t_m_pro_1_1_examples_1_1_text_mesh_spawner.html", null ],
        [ "TMP_ExampleScript_01", "class_t_m_pro_1_1_examples_1_1_t_m_p___example_script__01.html", null ],
        [ "TMP_FrameRateCounter", "class_t_m_pro_1_1_examples_1_1_t_m_p___frame_rate_counter.html", null ],
        [ "TMP_TextEventCheck", "class_t_m_pro_1_1_examples_1_1_t_m_p___text_event_check.html", null ],
        [ "TMP_TextInfoDebugTool", "class_t_m_pro_1_1_examples_1_1_t_m_p___text_info_debug_tool.html", null ],
        [ "TMP_TextSelector_A", "class_t_m_pro_1_1_examples_1_1_t_m_p___text_selector___a.html", null ],
        [ "TMP_TextSelector_B", "class_t_m_pro_1_1_examples_1_1_t_m_p___text_selector___b.html", null ],
        [ "TMP_UiFrameRateCounter", "class_t_m_pro_1_1_examples_1_1_t_m_p___ui_frame_rate_counter.html", null ],
        [ "TMPro_InstructionOverlay", "class_t_m_pro_1_1_examples_1_1_t_m_pro___instruction_overlay.html", null ],
        [ "VertexColorCycler", "class_t_m_pro_1_1_examples_1_1_vertex_color_cycler.html", null ],
        [ "VertexJitter", "class_t_m_pro_1_1_examples_1_1_vertex_jitter.html", null ],
        [ "VertexShakeA", "class_t_m_pro_1_1_examples_1_1_vertex_shake_a.html", null ],
        [ "VertexShakeB", "class_t_m_pro_1_1_examples_1_1_vertex_shake_b.html", null ],
        [ "VertexZoom", "class_t_m_pro_1_1_examples_1_1_vertex_zoom.html", null ],
        [ "WarpTextExample", "class_t_m_pro_1_1_examples_1_1_warp_text_example.html", null ]
      ] ],
      [ "TMP_DigitValidator", "class_t_m_pro_1_1_t_m_p___digit_validator.html", null ],
      [ "TMP_PhoneNumberValidator", "class_t_m_pro_1_1_t_m_p___phone_number_validator.html", null ],
      [ "TMP_TextEventHandler", "class_t_m_pro_1_1_t_m_p___text_event_handler.html", "class_t_m_pro_1_1_t_m_p___text_event_handler" ]
    ] ],
    [ "AudioManager", "class_audio_manager.html", "class_audio_manager" ],
    [ "CharacterData", "class_character_data.html", "class_character_data" ],
    [ "CharacterSelectionManager", "class_character_selection_manager.html", "class_character_selection_manager" ],
    [ "ChatController", "class_chat_controller.html", null ],
    [ "CombatCollisionManager", "class_combat_collision_manager.html", "class_combat_collision_manager" ],
    [ "CombatCollisionManagerTests", "class_combat_collision_manager_tests.html", "class_combat_collision_manager_tests" ],
    [ "CombatManager", "class_combat_manager.html", "class_combat_manager" ],
    [ "CrouchAttack", "class_crouch_attack.html", "class_crouch_attack" ],
    [ "DropdownSample", "class_dropdown_sample.html", null ],
    [ "EnemyHealthSystem", "class_enemy_health_system.html", "class_enemy_health_system" ],
    [ "EnemyHealthSystemTests", "class_enemy_health_system_tests.html", "class_enemy_health_system_tests" ],
    [ "EnergySystem", "class_energy_system.html", "class_energy_system" ],
    [ "EnergySystemTests", "class_energy_system_tests.html", "class_energy_system_tests" ],
    [ "EnvMapAnimator", "class_env_map_animator.html", null ],
    [ "ExtendedHitbox", "class_extended_hitbox.html", null ],
    [ "ExtendedHitboxTests", "class_extended_hitbox_tests.html", "class_extended_hitbox_tests" ],
    [ "HealthSystem", "class_health_system.html", "class_health_system" ],
    [ "HealthSystemTests", "class_health_system_tests.html", "class_health_system_tests" ],
    [ "Hitbox", "class_hitbox.html", "class_hitbox" ],
    [ "HitboxTests", "class_hitbox_tests.html", "class_hitbox_tests" ],
    [ "Jugar", "class_jugar.html", "class_jugar" ],
    [ "JumpWhitStrike", "class_jump_whit_strike.html", "class_jump_whit_strike" ],
    [ "NoPushOnHit", "class_no_push_on_hit.html", "class_no_push_on_hit" ],
    [ "PauseManager", "class_pause_manager.html", "class_pause_manager" ],
    [ "Player_", "class_player__.html", null ],
    [ "PlayerAttack", "class_player_attack.html", "class_player_attack" ],
    [ "PlayerAttackTests", "class_player_attack_tests.html", null ],
    [ "PlayerDefense", "class_player_defense.html", "class_player_defense" ],
    [ "PlayerDefenseTests", "class_player_defense_tests.html", null ],
    [ "PlayerMovement", "class_player_movement.html", "class_player_movement" ],
    [ "PlayerMovementTests", "class_player_movement_tests.html", null ],
    [ "PlayerSpecialAttack", "class_player_special_attack.html", "class_player_special_attack" ],
    [ "Prueba", "class_prueba.html", "class_prueba" ],
    [ "SpecialAttackData", "class_special_attack_data.html", "class_special_attack_data" ],
    [ "SpecialHitbox", "class_special_hitbox.html", "class_special_hitbox" ],
    [ "WinScreenAnimation", "class_win_screen_animation.html", "class_win_screen_animation" ]
];