Documentación Técnica: EnergySystem Class Reference
EnergySystem Class Reference
Public Member Functions
void GainEnergyFromDamage ()
Otorga energía al jugador cuando recibe un golpe del oponente. Incremento fijo de 2 puntos. Representa la mecánica de "cargarse al absorber daño", común en juegos de pelea.
void GainEnergyFromAttack (string attackName)
Otorga energía al jugador según el tipo de ataque que conectó. Cada tipo de ataque da una cantidad diferente:
void GainEnergyFromBlock ()
Otorga energía al jugador al activar el bloqueo (+3 puntos). Se llama solo al inicio del bloqueo, no mientras se mantiene presionado.
bool IsFull ()
Devuelve true si la barra de energía está completamente llena. Útil para verificar si el jugador puede activar una habilidad especial.
void ConsumeEnergy (int amount)
Consume una cantidad de energía al usar una habilidad especial. Clampea currentEnergy a 0 para evitar valores negativos. Actualiza la UI inmediatamente después.
Public Attributes
int maxEnergy = 100
Energía máxima acumulable. Define el techo del recurso. Configurable desde el Inspector. No debe ser 0 o negativo.
int currentEnergy
Energía actual del jugador en tiempo real. Se inicializa en 0 al comenzar la partida. Visible en Inspector para debug.
Image energyImage
Componente Image de Unity UI que muestra visualmente la barra de energía. Debe asignarse desde el Inspector. Si es null, la UI no se actualiza.
Private Member Functions
void Start ()
Start() — Se ejecuta una vez al iniciar. Carga el spritesheet de energía desde Resources, inicializa currentEnergy en 0 y actualiza la UI.
void UpdateEnergyUI ()
Actualiza el sprite de la barra de energía en la UI según currentEnergy. Calcula el índice proporcional en el spritesheet e invierte el orden para que el sprite 0 del array corresponda a energía llena.
Private Attributes
Sprite[] energySprites
Array de sprites cargados desde el spritesheet de energía. Se cargan automáticamente desde Resources/EnergyBar/emerald_counter-Sheet. Cada elemento corresponde a un frame del estado de la barra.
Detailed Description
Definition at line 27 of file EnergySystem.cs.
Member Function Documentation
ConsumeEnergy()
void EnergySystem.ConsumeEnergy (int amount) inline
Consume una cantidad de energía al usar una habilidad especial. Clampea currentEnergy a 0 para evitar valores negativos. Actualiza la UI inmediatamente después.
CUÁNDO SE LLAMA: Por scripts de habilidades o ataques especiales.
Parameters
amount Cantidad de energía a consumir.
Definition at line 157 of file EnergySystem.cs.
Referenced by EnergySystemTests.Energy_DoesNotGoBelowZero().
GainEnergyFromAttack()
void EnergySystem.GainEnergyFromAttack (string attackName) inline
Otorga energía al jugador según el tipo de ataque que conectó. Cada tipo de ataque da una cantidad diferente:
"Puñetazo" → +5 de energía
"Patada" → +10 de energía
CUÁNDO SE LLAMA: Desde Hitbox.cs y ExtendedHitbox.cs al conectar un golpe.
Parameters
attackName Nombre del ataque ejecutado ("Puñetazo" o "Patada").
Definition at line 110 of file EnergySystem.cs.
Referenced by EnergySystemTests.Energy_DoesNotExceedMaxEnergy(), EnergySystemTests.GainEnergyFromAttack_IncreasesEnergyByCorrectAmount(), ExtendedHitbox.OnTriggerEnter2D(), and Hitbox.OnTriggerStay2D().
GainEnergyFromBlock()
void EnergySystem.GainEnergyFromBlock () inline
Otorga energía al jugador al activar el bloqueo (+3 puntos). Se llama solo al inicio del bloqueo, no mientras se mantiene presionado.
CUÁNDO SE LLAMA: Desde PlayerDefense.cs en el frame en que isBlocking cambia a true.
Definition at line 128 of file EnergySystem.cs.
Referenced by PlayerDefenseTests.Block_GrantsEnergyWhenBlockingStarts(), EnergySystemTests.GainEnergyFromBlock_IncreasesEnergyByThree(), and PlayerDefense.Update().
GainEnergyFromDamage()
void EnergySystem.GainEnergyFromDamage () inline
Otorga energía al jugador cuando recibe un golpe del oponente. Incremento fijo de 2 puntos. Representa la mecánica de "cargarse al absorber daño", común en juegos de pelea.
CUÁNDO SE LLAMA: Desde Hitbox.cs cuando un golpe conecta en el jugador.
Definition at line 94 of file EnergySystem.cs.
Referenced by EnergySystemTests.GainEnergyFromDamage_IncreasesEnergyByTwo(), and Hitbox.OnTriggerStay2D().
IsFull()
bool EnergySystem.IsFull () inline
Devuelve true si la barra de energía está completamente llena. Útil para verificar si el jugador puede activar una habilidad especial.
Definition at line 144 of file EnergySystem.cs.
Referenced by EnergySystemTests.Energy_DoesNotExceedMaxEnergy(), and EnergySystemTests.Energy_DoesNotGoBelowZero().
Start()
void EnergySystem.Start () inline private
Start() — Se ejecuta una vez al iniciar. Carga el spritesheet de energía desde Resources, inicializa currentEnergy en 0 y actualiza la UI.
DEPENDENCIA: El archivo debe existir en Resources/EnergyBar/emerald_counter-Sheet.
Definition at line 74 of file EnergySystem.cs.
UpdateEnergyUI()
void EnergySystem.UpdateEnergyUI () inline private
Actualiza el sprite de la barra de energía en la UI según currentEnergy. Calcula el índice proporcional en el spritesheet e invierte el orden para que el sprite 0 del array corresponda a energía llena.
CUÁNDO SE EJECUTA: Llamado internamente después de cualquier cambio en currentEnergy.
LÓGICA DE INVERSIÓN: index normal = 0 → energía vacía (sprite de barra vacía) index invertido = (Length-1) - index → invierte el mapeo Resultado: index 0 del array = barra llena
Definition at line 180 of file EnergySystem.cs.
Referenced by ConsumeEnergy(), GainEnergyFromAttack(), GainEnergyFromBlock(), GainEnergyFromDamage(), and Start().
Member Data Documentation
currentEnergy
int EnergySystem.currentEnergy
Energía actual del jugador en tiempo real. Se inicializa en 0 al comenzar la partida. Visible en Inspector para debug.
Definition at line 44 of file EnergySystem.cs.
Referenced by PlayerDefenseTests.Block_GrantsEnergyWhenBlockingStarts(), ConsumeEnergy(), EnergySystemTests.Energy_DoesNotExceedMaxEnergy(), EnergySystemTests.Energy_DoesNotGoBelowZero(), GainEnergyFromAttack(), EnergySystemTests.GainEnergyFromAttack_IncreasesEnergyByCorrectAmount(), GainEnergyFromBlock(), EnergySystemTests.GainEnergyFromBlock_IncreasesEnergyByThree(), GainEnergyFromDamage(), EnergySystemTests.GainEnergyFromDamage_IncreasesEnergyByTwo(), IsFull(), Start(), and UpdateEnergyUI().
energyImage
Image EnergySystem.energyImage
Componente Image de Unity UI que muestra visualmente la barra de energía. Debe asignarse desde el Inspector. Si es null, la UI no se actualiza.
Definition at line 50 of file EnergySystem.cs.
Referenced by UpdateEnergyUI().
energySprites
Sprite [] EnergySystem.energySprites private
Array de sprites cargados desde el spritesheet de energía. Se cargan automáticamente desde Resources/EnergyBar/emerald_counter-Sheet. Cada elemento corresponde a un frame del estado de la barra.
Definition at line 61 of file EnergySystem.cs.
Referenced by Start(), and UpdateEnergyUI().
maxEnergy
int EnergySystem.maxEnergy = 100
Energía máxima acumulable. Define el techo del recurso. Configurable desde el Inspector. No debe ser 0 o negativo.
Definition at line 37 of file EnergySystem.cs.
Referenced by EnergySystemTests.Energy_DoesNotExceedMaxEnergy(), EnergySystemTests.Energy_DoesNotGoBelowZero(), GainEnergyFromAttack(), GainEnergyFromBlock(), GainEnergyFromDamage(), IsFull(), and UpdateEnergyUI().
The documentation for this class was generated from the following file:
spritesheets/Scripts/EnergySystem.cs