Documentación Técnica: EnergySystemTests Class Reference
EnergySystemTests Class Reference
TEST SUITE: EnergySystem.
Public Member Functions
void TearDown ()
Limpia el GameObject después de cada test para evitar interferencia entre pruebas.
IEnumerator GainEnergyFromAttack_IncreasesEnergyByCorrectAmount ()
Verifica que diferentes ataques generan distinta cantidad de energía:
IEnumerator GainEnergyFromDamage_IncreasesEnergyByTwo ()
Verifica que recibir daño también genera energía (+2).
IEnumerator GainEnergyFromBlock_IncreasesEnergyByThree ()
Verifica que bloquear genera energía (+3).
IEnumerator Energy_DoesNotExceedMaxEnergy ()
Verifica que la energía no puede superar maxEnergy.
IEnumerator Energy_DoesNotGoBelowZero ()
Verifica que la energía nunca baja de 0.
Private Member Functions
EnergySystem CreateEnergySystem ()
Crea un jugador simulado con EnergySystem. No se asigna UI intencionalmente (energyImage = null), ya que no se está probando la interfaz.
Private Attributes
GameObject _playerGO
Detailed Description
TEST SUITE: EnergySystem.
PROPÓSITO: Validar el sistema de energía del jugador en combate.
Este sistema controla cómo se gana y consume energía a través de:
Ataques (puñetazo, patada)
Recibir daño
Bloquear
También valida límites:
No puede superar el máximo de energía
No puede bajar de 0
DEPENDENCIA IMPORTANTE: EnergySystem depende de UI (energyImage), pero en tests se deja null. Esto genera LogError controlado que se ignora con LogAssert.
Definition at line 25 of file EnergySystemTests.cs.
Member Function Documentation
CreateEnergySystem()
EnergySystem EnergySystemTests.CreateEnergySystem () inline private
Crea un jugador simulado con EnergySystem. No se asigna UI intencionalmente (energyImage = null), ya que no se está probando la interfaz.
Definition at line 40 of file EnergySystemTests.cs.
Referenced by Energy_DoesNotExceedMaxEnergy(), Energy_DoesNotGoBelowZero(), GainEnergyFromAttack_IncreasesEnergyByCorrectAmount(), GainEnergyFromBlock_IncreasesEnergyByThree(), and GainEnergyFromDamage_IncreasesEnergyByTwo().
Energy_DoesNotExceedMaxEnergy()
IEnumerator EnergySystemTests.Energy_DoesNotExceedMaxEnergy () inline
Verifica que la energía no puede superar maxEnergy.
Definition at line 157 of file EnergySystemTests.cs.
Energy_DoesNotGoBelowZero()
IEnumerator EnergySystemTests.Energy_DoesNotGoBelowZero () inline
Verifica que la energía nunca baja de 0.
Definition at line 181 of file EnergySystemTests.cs.
GainEnergyFromAttack_IncreasesEnergyByCorrectAmount()
IEnumerator EnergySystemTests.GainEnergyFromAttack_IncreasesEnergyByCorrectAmount () inline
Verifica que diferentes ataques generan distinta cantidad de energía:
Puñetazo → +5
Patada → +10
Desconocido → +0
Definition at line 71 of file EnergySystemTests.cs.
GainEnergyFromBlock_IncreasesEnergyByThree()
IEnumerator EnergySystemTests.GainEnergyFromBlock_IncreasesEnergyByThree () inline
Verifica que bloquear genera energía (+3).
Definition at line 134 of file EnergySystemTests.cs.
GainEnergyFromDamage_IncreasesEnergyByTwo()
IEnumerator EnergySystemTests.GainEnergyFromDamage_IncreasesEnergyByTwo () inline
Verifica que recibir daño también genera energía (+2).
Definition at line 111 of file EnergySystemTests.cs.
TearDown()
void EnergySystemTests.TearDown () inline
Limpia el GameObject después de cada test para evitar interferencia entre pruebas.
Definition at line 55 of file EnergySystemTests.cs.
Member Data Documentation
_playerGO
GameObject EnergySystemTests._playerGO private
Definition at line 30 of file EnergySystemTests.cs.
Referenced by CreateEnergySystem(), and TearDown().
The documentation for this class was generated from the following file:
Tests/PlayMode/EnergySystemTests.cs